//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATMSystemGroup4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Account
    {
        public Account()
        {
            this.Cards = new HashSet<Card>();
        }

        [Required(ErrorMessage = "A AccountID is required")]
        public int AccountID { get; set; }
        public Nullable<int> CustID { get; set; }
        public string AccountNo { get; set; }
        public Nullable<int> ODID { get; set; }
        public Nullable<int> WDID { get; set; }

       // [Required(ErrorMessage = "Is required")]
        public Nullable<decimal> Balance { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual OverDraftLimit OverDraftLimit { get; set; }
        public virtual WithDrawLimit WithDrawLimit { get; set; }
        public virtual ICollection<Card> Cards { get; set; }
    }
}
