//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATMSystemGroup4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ATM_SystemEntities : DbContext
    {
        public ATM_SystemEntities()
            : base("name=ATM_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<ATM> ATMs { get; set; }
        public DbSet<Card> Cards { get; set; }
        public DbSet<Config> Configs { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Log> Logs { get; set; }
        public DbSet<LogType> LogTypes { get; set; }
        public DbSet<MoneyType> MoneyTypes { get; set; }
        public DbSet<OverDraftLimit> OverDraftLimits { get; set; }
        public DbSet<Stock> Stocks { get; set; }
        public DbSet<WithDrawLimit> WithDrawLimits { get; set; }
    }
}
