//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATMSystemGroup4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public int ConID { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<decimal> MinWithDraw { get; set; }
        public Nullable<decimal> MaxWithDraw { get; set; }
        public Nullable<int> NumPerPage { get; set; }
    }
}
