//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATMSystemGroup4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoneyType
    {
        public MoneyType()
        {
            this.Stocks = new HashSet<Stock>();
        }
    
        public int MoneyTypeID { get; set; }
        public Nullable<decimal> MoneyValue { get; set; }
    
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
